# Generated by Django 4.2.1 on 2023-05-28 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_request"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="course_id",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="student_pn",
            new_name="student_phone_number",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="teacher_id",
            new_name="teacher",
        ),
    ]
